### PR TITLE
fix: update dependencies, CI/CD workflows and code formatting

### PR DESCRIPTION
**Pull request by HJunyuan**
Please help to ensure the rendered templates work as expected.

# Changes
- Add `.prettierrc` file to ensure consistency in code formatting
- Remove `.circleci/config.yml` workflow since there is already a GitHub Actions workflow
- Use Node v14 for all workflows (`.nvmrc`, `.github/workflows/ci-pull-request-open.yml`, `.github/workflows/dependency-check.yml`)
- Dependency updates
- Code formatting

### CODE REVIEW

**Review by causztic — APPROVED** [review]

**Comment by causztic** [comment]
might need to update the types

**Comment by HJunyuan** [comment]
`@storybook/addon-knobs` has been deprecated in favour of `@storybook/addon-controls` ([source](https://github.com/storybookjs/storybook/discussions/15060)).

As such, will be removing addon-knobs from this repo and leave it without controls since we aren't really utilising this feature at the moment.

**Comment by HJunyuan** [comment]
`react-docgen-typescript-loader` seems to be broken as well - removing it from the repo in the meantime.

**Comment by causztic** [comment]
This PR is a big one! :o

**Comment by HJunyuan** [comment]
😵  It's mostly code formatting. I've tried to update as much as I can but there are still a few packages that are not updated yet (e.g. Jest, Webpack, etc.).

**Review by causztic — APPROVED** [review]

**Pull request merged**
